version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/mysite
permissions:
  - object: /var/www
    owner: "nginx"
    group: "nginx"

AfterInstall:
    - location: scripts/migrate.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/restart-server.sh
      timeout: 120
      runas: root
